# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-05 14:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Details',
            new_name='Detail',
        ),
        migrations.RenameField(
            model_name='detail',
            old_name='details',
            new_name='detail',
        ),
    ]
