# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-05 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170705_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='detail',
            new_name='details',
        ),
        migrations.AlterField(
            model_name='detail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Profil', verbose_name='Utilisateur concerné'),
        ),
    ]
