# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-26 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170705_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='telephone',
            field=models.CharField(max_length=20, null=True, verbose_name='N° de téléphone'),
        ),
    ]
