# -*- coding: utf-8 -*-
""" Generated by Django 1.11.11 on 2018-03-24 18:23 """
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    """The initial migration"""

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('test', models.BooleanField(default=False)),
            ],
        ),
    ]
