# -*- coding: utf-8 -*-
""" Generated by Django 1.11.11 on 2018-04-10 21:11 """
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """Création du profil"""

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('utilisateurs', '0002_delete_vide'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=20, null=True,
                                               verbose_name='N° de téléphone'
                                               )),
                ('benevole', models.BooleanField(default=False)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.
                                              deletion.CASCADE,
                                              to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
