# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-24 18:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='vide',
        ),
    ]
